CUSTOM_KEYWORDS = [
    {"keyword": "payme", "category": "fraud", "search_place": "url", "allowed_for_host": "payme.uz"},
    {"keyword": "click", "category": "fraud", "search_place": "url", "allowed_for_host": "click.uz"},
    {"keyword": "paynet", "category": "fraud", "search_place": "url", "allowed_for_host": "paynet.uz"},
    {"keyword": "uzcard", "category": "fraud", "search_place": "url", "allowed_for_host": "uzcard.uz"},
    {"keyword": "anorbank", "category": "fraud", "search_place": "url", "allowed_for_host": "anorbankanorbank.uz"},
    {"keyword": "kapitalbank", "category": "fraud", "search_place": "url", "allowed_for_host": "kapitalbank.uz"},
    {"keyword": "oson", "category": "fraud", "search_place": "url", "allowed_for_host": "oson.uz"},
    {"keyword": "bank.uz", "category": "fraud", "search_place": "url", "allowed_for_host": "bank.uz"},

    {"keyword": "jaholat", "category": "extremist", "search_place": "url"},
    {"keyword": "jihod", "category": "extremist", "search_place": "all"},
    {"keyword": "jihad", "category": "extremist", "search_place": "all"},
    {"keyword": "hizb-ut", "category": "extremist", "search_place": "all"},
    {"keyword": "ut-tahrir", "category": "extremist", "search_place": "all"},

    {"keyword": "sex", "category": "porn", "search_place": "all"},
    {"keyword": "porn", "category": "porn", "search_place": "all"},
    {"keyword": "seks", "category": "porn", "search_place": "all"},

    {"keyword": "narko", "category": "drugs", "search_place": "url"},
    {"keyword": "gashish", "category": "drugs", "search_place": "all"},
    {"keyword": "konoplya", "category": "drugs", "search_place": "all"},
    {"keyword": "zakladki", "category": "drugs", "search_place": "all"},
    {"keyword": "gashish", "category": "drugs", "search_place": "all"},
    {"keyword": "amfetamin", "category": "drugs", "search_place": "all"},
    {"keyword": "amphetamine", "category": "drugs", "search_place": "all"},
    {"keyword": "mdpv", "category": "drugs", "search_place": "all"},
    {"keyword": "metamfetamin", "category": "drugs", "search_place": "all"},
    {"keyword": "methamphetamin", "category": "drugs", "search_place": "all"},

    {"keyword": "casino", "category": "casino", "search_place": "url"},
    {"keyword": "1xb", "category": "casino", "search_place": "url"},
    {"keyword": "bet", "category": "casino", "search_place": "url"},
    {"keyword": "stavki", "category": "casino", "search_place": "url"},

    {"keyword": "amateur", "category": "escort", "search_place": "url"},
    {"keyword": "privat", "category": "escort", "search_place": "url"},
    {"keyword": "suchki", "category": "escort", "search_place": "url"},
    {"keyword": "girls", "category": "escort", "search_place": "url"},
    {"keyword": "devushki", "category": "escort", "search_place": "url"},
    {"keyword": "escort", "category": "escort", "search_place": "url"},
    {"keyword": "eskort", "category": "escort", "search_place": "url"},
]