from utils.enums import KeywordCategory

KEYWORD_CATEGORIES = {
    "amateur": KeywordCategory.ESCORT,
    "porn": KeywordCategory.PORN,
    "sex": KeywordCategory.PORN,
    "seks": KeywordCategory.PORN,
    "privat": KeywordCategory.ESCORT,
    "suchki": KeywordCategory.ESCORT,
    "girls": KeywordCategory.ESCORT,
    "devushki": KeywordCategory.ESCORT,
    "escort": KeywordCategory.ESCORT,
    "eskort": KeywordCategory.ESCORT,
    "casino": KeywordCategory.CASINO,
    "1xb": KeywordCategory.CASINO,
    "bet": KeywordCategory.CASINO,
    "stavki": KeywordCategory.CASINO,
    "narko": KeywordCategory.DRUGS,
    "gashish": KeywordCategory.DRUGS,
    "konoplya": KeywordCategory.DRUGS,
    "zakladki": KeywordCategory.DRUGS,
    "gashish": KeywordCategory.DRUGS,
    "amfetamin": KeywordCategory.DRUGS,
    "amphetamine": KeywordCategory.DRUGS,
    "mdpv": KeywordCategory.DRUGS,
    "metamfetamin": KeywordCategory.DRUGS,
}