# Generated by Django 4.2.9 on 2024-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_host_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="category",
            field=models.CharField(
                choices=[
                    ("extremist", "Террористический ресурс"),
                    ("fraud", "Мошенничество и фишинг"),
                    ("porn", "Порно"),
                    ("escort", "Эскорт"),
                    ("drugs", "Наркотики"),
                    ("casino", "Казино"),
                    ("betting", "Ставки"),
                    ("other", "Другое"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="category",
            field=models.CharField(
                choices=[
                    ("extremist", "Террористический ресурс"),
                    ("fraud", "Мошенничество и фишинг"),
                    ("porn", "Порно"),
                    ("escort", "Эскорт"),
                    ("drugs", "Наркотики"),
                    ("casino", "Казино"),
                    ("betting", "Ставки"),
                    ("curse", "Матерное слово"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
